# Generated by Django 4.2.10 on 2024-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('circle', models.CharField(max_length=255)),
                ('dist', models.CharField(max_length=255)),
                ('div', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
    ]
