# Generated by Django 4.2.10 on 2024-02-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalapp', '0003_postaladdress_branch_type_postaladdress_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postal',
            old_name='area',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='postal',
            old_name='code',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='branch_type',
            new_name='Branch_type',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='circle',
            new_name='Circle',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='dist',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='div',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='pincode',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='place',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='state',
            new_name='State',
        ),
        migrations.AddField(
            model_name='postal',
            name='Branch_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postal',
            name='Circle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postal',
            name='Country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postal',
            name='District',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postal',
            name='Division',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postal',
            name='Region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postal',
            name='State',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
